# Generated by Django 5.1.6 on 2025-02-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_activationtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivationToken",
        ),
    ]
