# Generated by Django 5.1.6 on 2025-03-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_avatar_customuser_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_block_user", "Блокирование пользователей"),
                    ("can_list_users", "Просмотр списка пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
