# Generated by Django 5.1.6 on 2025-02-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=50, verbose_name="Тема письма")),
                ("text", models.TextField(verbose_name="Содержание письма")),
            ],
            options={
                "verbose_name": "Сообщение рассылки",
                "verbose_name_plural": "Сообщения рассылки",
            },
        ),
    ]
