# Generated by Django 5.1.6 on 2025-02-19 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершена"),
                    ("created", "Создана"),
                    ("started", "Запущена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Введите корректный адрес электронной почты."
                    )
                ],
                verbose_name="Электронная почта",
            ),
        ),
        migrations.CreateModel(
            name="AttemptToSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_of_attempt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("successfully", "Успешно"),
                            ("unsuccessfully", "Неуспешно"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
