# Generated by Django 5.1.6 on 2025-02-19 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_status_alter_mailingrecipient_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempttosend",
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.CharField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Введите корректный адрес электронной почты."
                    )
                ],
                verbose_name="Электронная почта",
            ),
        ),
    ]
