# Generated by Django 5.1.6 on 2025-02-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing",
            "0005_alter_attempttosend_options_alter_mailing_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attempttosend",
            name="server_response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ответ почтового сервера"
            ),
        ),
        migrations.AlterField(
            model_name="attempttosend",
            name="time_of_attempt",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время попытки"
            ),
        ),
    ]
