# Generated by Django 5.1.6 on 2025-03-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_mailing_owner_mailingrecipient_owner_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailing", "Просмотр рассылки"),
                    ("can_block_user", "Блокирование пользователей"),
                    ("can_disable_mailing", "Отключение рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "permissions": [
                    (
                        "can_view_mailingrecipient",
                        "Просмотр получателей рассылки",
                    )
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_message", "Просмотр сообщений рассылки")
                ],
                "verbose_name": "Сообщение рассылки",
                "verbose_name_plural": "Сообщения рассылки",
            },
        ),
    ]
