# Generated by Django 5.1.6 on 2025-03-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing",
            "0008_alter_mailing_options_alter_mailingrecipient_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailing", "Просмотр рассылки"),
                    ("can_block_user", "Блокирование пользователей"),
                    ("can_disable_mailing", "Отключение рассылки"),
                    ("can_list_users", "Просмотр списка пользователей"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
